export const FETCH_PRODUCT_DATA_START = 'FETCH_PRODUCT_DATA_START';
export const FETCH_PRODUCT_DATA_SUCCESS = 'FETCH_PRODUCT_DATA_SUCCESS';
export const FETCH_PRODUCT_DATA_FAIL = 'FETCH_PRODUCT_DATA_FAIL';
export const SET_PRODUCT_DATA = 'SET_PRODUCT_DATA';

export const SET_ADDRESS_DATA = 'SET_ADDRESS_DATA';

export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';

export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';

export const SET_CHECKED_STATE = 'SET_CHECKED_STATE';